#!/usr/bin/env bash
# 07 — Generate config.js consumed by index.html. This file points the front-end
# at the live Logic App trigger URLs and bakes the App Insights connection string
# in for client-side telemetry.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/parameters.sh"

[[ -f "$SCRIPT_DIR/.state.endpoints.json" ]] || fail "Run 05-logicapps.sh first"
ENDPOINTS="$(cat "$SCRIPT_DIR/.state.endpoints.json")"
APPI_CONN="$(grep '^APPI_CONN=' "$SCRIPT_DIR/.state.monitor" 2>/dev/null | cut -d= -f2- || true)"
SWA_HOST="$(grep '^SWA_HOST='   "$SCRIPT_DIR/.state.swa"     2>/dev/null | cut -d= -f2- || true)"

OUT="$(cd "$SCRIPT_DIR/.." && pwd)/config.js"

cat >"$OUT" <<EOF
// Auto-generated by infra/07-write-config.sh — do not edit by hand.
// Frontend pulls live Azure Logic App URLs from this file.
window.__TV_CONFIG__ = {
  compliance: { primaryRegion: "$LOCATION" },
  security:   { minPasswordLength: 8 },
  ops:        {
    appInsightsConnectionString: "$APPI_CONN"
  },
  endpoints:  $ENDPOINTS,
  swa:        { host: "$SWA_HOST" }
};
EOF

ok "Wrote $OUT"
