name: Deploy ThreatVault Frontend to Azure Storage

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - uses: actions/checkout@v4

      - name: Upload to Blob Storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            # Deploy using the Storage Key directly
            az storage blob upload-batch \
              --account-name sttv5fb957 \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
              -d '$web' -s . \
              --pattern "index.html" --overwrite true
            
            az storage blob upload-batch \
              --account-name sttv5fb957 \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
              -d '$web' -s . \
              --pattern "config.js" --overwrite true
